### PR TITLE
Migrate to using SmallRye Config for MP Config implementation

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Note: requires SmallRye Config 1.3.2 to be released with fix for CNFE

**Comment by michalszynkiewicz** [comment]
@kenfinnigan I see Smallrye Config 1.3.2 already hit the Central. Does it make this change ready for review (and merge)?

**Comment by kenfinnigan** [comment]
It does.

I don't have the ability to release any of this though, so we need @jmesnil for that

**Comment by jmesnil** [comment]
I've released all artifacts for wildfly-microprofile-config 1.3 with this PR merged: https://github.com/wildfly-extras/wildfly-microprofile-config/releases/tag/1.3.0

**Comment by kenfinnigan** [comment]
Thanks @jmesnil!

**Comment by kenfinnigan** [comment]
@jmesnil, do they get released to JBoss Nexus or Sonatype directly?

If the former, do you know how long it takes to reach central?

**Comment by jmesnil** [comment]
They are released in JBoss Nexus https://repository.jboss.org/nexus/service/local/repositories/releases/content/org/wildfly/wildfly-microprofile-config/1.3.0/

I have no idea how long they take to reach central though...

**Comment by kenfinnigan** [comment]
Should I expect to see the 1.3.0 artifacts in https://repository.jboss.org/nexus/content/groups/public-jboss/org/wildfly/wildfly-microprofile-config-feature-pack/ yet?

**Comment by jmesnil** [comment]
I see them at https://repository.jboss.org/nexus/content/groups/public-jboss/org/wildfly/wildfly-microprofile-config-feature-pack/1.3.0/

**Comment by kenfinnigan** [comment]
I can now see that in Maven, but I'm wondering if the `microprofile-config-api` got released properly as I changed the groupId to `io.thorntail`. Especially as https://repository.jboss.org/nexus/content/groups/public-jboss/io/thorntail/ doesn't appear to show it.

Do you recall if there were warnings about it failing on that artifact?

I might try to push that artifact tag directly to Sonatype

**Comment by jmesnil** [comment]
it has been released in 3rd party repository: 
https://repository.jboss.org/nexus/service/local/repositories/thirdparty-releases/content/io/thorntail/microprofile-config-api/1.3.0/microprofile-config-api-1.3.0.ja

I remember it was in a separate staging repo. The other staging repo belonged to the "JBoss Releases" repository while this artifact was in another one. I did not pay much attention to that (as the groupId was changed).
Maybe nexus is not configured to properly release `io.thorntail` artifacts as "JBoss" release...

**Comment by kenfinnigan** [comment]
Do you think it would cause a problem if I deployed that artifact directly to Nexus?

**Pull request merged**
